
server:
  port: 8084



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client
    username: root
    password: Sreenivas@123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: Donar-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
#  data:
#    redis:
#      host: localhost
#      port: 6739
#  cache:
#    cache-names:
#      - Donar

eureka:
  instance:
    prefer-ip-address: true
  client:
    eureka-server-connect-timeout-seconds: 6000
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#feign.
#client.config.default.connectTimeout: 160000000
#feign.client.config.default.readTimeout: 160000000

